apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  #name: java-spring-boot2-manual-pipeline-run
  generateName: nodejs-manual-bluecompute-web-pr-
spec:
  serviceAccount: kabanero-operator
  timeout: "1h0m0s"
  pipelineRef:
    name: nodejs-build-deploy-pipeline
  resources:
    - name: git-source
      resourceRef:
        name: git-source
    - name: docker-image
      resourceRef:
        name: docker-image
